In [1]:
import pandas as pd
import numpy as np

In [4]:
cfpb = pd.read_csv('cfpb_LI_Loan_Requests_2022.csv')
cfpb.head()

C:\Users\home1\AppData\Local\Temp\ipykernel_22464\4049858040.py:1: DtypeWarning: Columns (22,23,24,26,27,28,29,30,31,32,33,38,44) have mixed types. Specify dtype option on import or set low_memory=False.
  cfpb = pd.read_csv('cfpb_LI_Loan_Requests_2022.csv')

,activity_year,lei,derived_msa-md,state_code,county_code,census_tract,conforming_loan_limit,derived_loan_product_type,derived_dwelling_category,derived_ethnicity,...,denial_reason-2,denial_reason-3,denial_reason-4,tract_population,tract_minority_population_percent,ffiec_msa_md_median_family_income,tract_to_msa_income_percentage,tract_owner_occupied_units,tract_one_to_four_family_homes,tract_median_age_of_housing_units
0,2022,KD3XUN7C6T14HNAYLU02,35004,NY,36103,3.610316e+10,NaN,Conventional:First Lien,Multifamily:Site-Built,Ethnicity Not Available,...,NaN,NaN,NaN,4820,26.47,146400,84,1208,1493,52
1,2022,KD3XUN7C6T14HNAYLU02,35004,NY,36059,3.605952e+10,NaN,Conventional:First Lien,Multifamily:Site-Built,Ethnicity Not Available,...,NaN,NaN,NaN,5560,54.82,146400,75,1013,1834,68
2,2022,KD3XUN7C6T14HNAYLU02,35004,NY,36059,3.605952e+10,NaN,Conventional:First Lien,Multifamily:Site-Built,Ethnicity Not Available,...,NaN,NaN,NaN,5560,54.82,146400,75,1013,1834,68
3,2022,KD3XUN7C6T14HNAYLU02,35004,NY,36103,3.610316e+10,NaN,Conventional:First Lien,Multifamily:Site-Built,Ethnicity Not Available,...,NaN,NaN,NaN,4820,26.47,146400,84,1208,1493,52
4,2022,KD3XUN7C6T14HNAYLU02,35004,NY,36103,3.610316e+10,NaN,Conventional:First Lien,Multifamily:Site-Built,Ethnicity Not Available,...,NaN,NaN,NaN,2822,21.90,146400,98,843,971,34

In [5]:
cfpb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115871 entries, 0 to 115870
Data columns (total 99 columns):
 #   Column                                    Non-Null Count   Dtype
---  ------                                    --------------   -----
 0   activity_year                             115871 non-null  int64
 1   lei                                       115871 non-null  object
 2   derived_msa-md                            115871 non-null  int64
 3   state_code                                115869 non-null  object
 4   county_code                               115871 non-null  int64
 5   census_tract                              115857 non-null  float64
 6   conforming_loan_limit                     115697 non-null  object
 7   derived_loan_product_type                 115871 non-null  object
 8   derived_dwelling_category                 115871 non-null  object
 9   derived_ethnicity                         115871 non-null  object
 10  derived_race                              115871 non-null  object
 11  derived_sex                               115871 non-null  object
 12  action_taken                              115871 non-null  int64
 13  purchaser_type                            115871 non-null  int64
 14  preapproval                               115871 non-null  int64
 15  loan_type                                 115871 non-null  int64
 16  loan_purpose                              115871 non-null  int64
 17  lien_status                               115871 non-null  int64
 18  reverse_mortgage                          115871 non-null  int64
 19  open-end_line_of_credit                   115871 non-null  int64
 20  business_or_commercial_purpose            115871 non-null  int64
 21  loan_amount                               115871 non-null  float64
 22  loan_to_value_ratio                       82350 non-null   object
 23  interest_rate                             75788 non-null   object
 24  rate_spread                               59754 non-null   object
 25  hoepa_status                              115871 non-null  int64
 26  total_loan_costs                          56206 non-null   object
 27  total_points_and_fees                     761 non-null     object
 28  origination_charges                       56527 non-null   object
 29  discount_points                           33832 non-null   object
 30  lender_credits                            19638 non-null   object
 31  loan_term                                 114516 non-null  object
 32  prepayment_penalty_term                   8835 non-null    object
 33  intro_rate_period                         35197 non-null   object
 34  negative_amortization                     115871 non-null  int64
 35  interest_only_payment                     115871 non-null  int64
 36  balloon_payment                           115871 non-null  int64
 37  other_nonamortizing_features              115871 non-null  int64
 38  property_value                            96084 non-null   object
 39  construction_method                       115871 non-null  int64
 40  occupancy_type                            115871 non-null  int64
 41  manufactured_home_secured_property_type   115871 non-null  int64
 42  manufactured_home_land_property_interest  115871 non-null  int64
 43  total_units                               115871 non-null  object
 44  multifamily_affordable_units              791 non-null     object
 45  income                                    106394 non-null  float64
 46  debt_to_income_ratio                      81208 non-null   object
 47  applicant_credit_score_type               115871 non-null  int64
 48  co-applicant_credit_score_type            115871 non-null  int64
 49  applicant_ethnicity-1                     115783 non-null  float64
 50  applicant_ethnicity-2                     4809 non-null    float64
 51  applicant_ethnicity-3                     90 non-null      float64
 52  applicant_ethnicity-4                     3 non-null       float64
 53  applicant_ethnicity-5                     0 non-null       float64
 54  co-applicant_ethnicity-1                  115845 non-null  float64
 55  co-applicant_ethnicity-2                  2029 non-null    float64
 56  co-applicant_ethnicity-3                  38 non-null      float64
 57  co-applicant_ethnicity-4                  2 non-null       float64
 58  co-applicant_ethnicity-5                  0 non-null       float64
 59  applicant_ethnicity_observed              115871 non-null  int64
 60  co-applicant_ethnicity_observed           115871 non-null  int64
 61  applicant_race-1                          115826 non-null  float64
 62  applicant_race-2                          7063 non-null    float64
 63  applicant_race-3                          353 non-null     float64
 64  applicant_race-4                          18 non-null      float64
 65  applicant_race-5                          3 non-null       float64
 66  co-applicant_race-1                       115865 non-null  float64
 67  co-applicant_race-2                       2987 non-null    float64
 68  co-applicant_race-3                       162 non-null     float64
 69  co-applicant_race-4                       7 non-null       float64
 70  co-applicant_race-5                       0 non-null       float64
 71  applicant_race_observed                   115871 non-null  int64
 72  co-applicant_race_observed                115871 non-null  int64
 73  applicant_sex                             115871 non-null  int64
 74  co-applicant_sex                          115871 non-null  int64
 75  applicant_sex_observed                    115871 non-null  int64
 76  co-applicant_sex_observed                 115871 non-null  int64
 77  applicant_age                             115871 non-null  object
 78  co-applicant_age                          115871 non-null  object
 79  applicant_age_above_62                    105692 non-null  object
 80  co-applicant_age_above_62                 48370 non-null   object
 81  submission_of_application                 115871 non-null  int64
 82  initially_payable_to_institution          115871 non-null  int64
 83  aus-1                                     115871 non-null  int64
 84  aus-2                                     10607 non-null   float64
 85  aus-3                                     2327 non-null    float64
 86  aus-4                                     132 non-null     float64
 87  aus-5                                     128 non-null     float64
 88  denial_reason-1                           115871 non-null  int64
 89  denial_reason-2                           4774 non-null    float64
 90  denial_reason-3                           818 non-null     float64
 91  denial_reason-4                           81 non-null      float64
 92  tract_population                          115871 non-null  int64
 93  tract_minority_population_percent         115871 non-null  float64
 94  ffiec_msa_md_median_family_income         115871 non-null  int64
 95  tract_to_msa_income_percentage            115871 non-null  int64
 96  tract_owner_occupied_units                115871 non-null  int64
 97  tract_one_to_four_family_homes            115871 non-null  int64
 98  tract_median_age_of_housing_units         115871 non-null  int64
dtypes: float64(31), int64(41), object(27)
memory usage: 87.5+ MB

Notes:  
- Some categories look like they are partially one-hot-encoded already, but not completely (Not boolean values? need to check if binary)  
- A lot of personal information about applicants  
- A lot of columns with null values (will need to decide if drop, impute etc.)